/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package ex002poo;

public class App {
    public static void main(String[] args) {
        Horario horario1 = new Horario(12, 30, 45);
        Horario horario2 = new Horario(10, 15, 30);

        System.out.println("Horario 1: " + horario1);
        System.out.println("Horario 2: " + horario2);
        System.out.println("Diferença em segundos: " + horario1.diferencaEmSegundos(horario2));
    }
}
